//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormularioDePrueba.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://Intec/")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        private int EstadoField;
        
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ImagenUsuario {
            get {
                return this.ImagenUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenUsuarioField, value) != true)) {
                    this.ImagenUsuarioField = value;
                    this.RaisePropertyChanged("ImagenUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://Intec/")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaField;
        
        private decimal PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FormularioDePrueba.ServiceReference1.Imagenes[] ImágenesField;
        
        private int StockField;
        
        private double calificacionField;
        
        private System.DateTime FechaDeCreacionField;
        
        private System.DateTime FechaUltimaModificacionField;
        
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenPrincipalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public FormularioDePrueba.ServiceReference1.Imagenes[] Imágenes {
            get {
                return this.ImágenesField;
            }
            set {
                if ((object.ReferenceEquals(this.ImágenesField, value) != true)) {
                    this.ImágenesField = value;
                    this.RaisePropertyChanged("Imágenes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double calificacion {
            get {
                return this.calificacionField;
            }
            set {
                if ((this.calificacionField.Equals(value) != true)) {
                    this.calificacionField = value;
                    this.RaisePropertyChanged("calificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime FechaDeCreacion {
            get {
                return this.FechaDeCreacionField;
            }
            set {
                if ((this.FechaDeCreacionField.Equals(value) != true)) {
                    this.FechaDeCreacionField = value;
                    this.RaisePropertyChanged("FechaDeCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime FechaUltimaModificacion {
            get {
                return this.FechaUltimaModificacionField;
            }
            set {
                if ((this.FechaUltimaModificacionField.Equals(value) != true)) {
                    this.FechaUltimaModificacionField = value;
                    this.RaisePropertyChanged("FechaUltimaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ImagenPrincipal {
            get {
                return this.ImagenPrincipalField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenPrincipalField, value) != true)) {
                    this.ImagenPrincipalField = value;
                    this.RaisePropertyChanged("ImagenPrincipal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Imagenes", Namespace="http://Intec/")]
    [System.SerializableAttribute()]
    public partial class Imagenes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        private System.DateTime FechaDeAsignacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime FechaDeAsignacion {
            get {
                return this.FechaDeAsignacionField;
            }
            set {
                if ((this.FechaDeAsignacionField.Equals(value) != true)) {
                    this.FechaDeAsignacionField = value;
                    this.RaisePropertyChanged("FechaDeAsignacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Marca", Namespace="http://Intec/")]
    [System.SerializableAttribute()]
    public partial class Marca : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Logo {
            get {
                return this.LogoField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoField, value) != true)) {
                    this.LogoField = value;
                    this.RaisePropertyChanged("Logo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://Intec/")]
    [System.SerializableAttribute()]
    public partial class Categoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Intec/", ConfigurationName="ServiceReference1.ServicioASoap")]
    public interface ServicioASoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento email del espacio de nombres http://Intec/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/EliminarUsuarioFirebase", ReplyAction="*")]
        FormularioDePrueba.ServiceReference1.EliminarUsuarioFirebaseResponse EliminarUsuarioFirebase(FormularioDePrueba.ServiceReference1.EliminarUsuarioFirebaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/EliminarUsuarioFirebase", ReplyAction="*")]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.EliminarUsuarioFirebaseResponse> EliminarUsuarioFirebaseAsync(FormularioDePrueba.ServiceReference1.EliminarUsuarioFirebaseRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento email del espacio de nombres http://Intec/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/IniciarSesionFirebase", ReplyAction="*")]
        FormularioDePrueba.ServiceReference1.IniciarSesionFirebaseResponse IniciarSesionFirebase(FormularioDePrueba.ServiceReference1.IniciarSesionFirebaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/IniciarSesionFirebase", ReplyAction="*")]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.IniciarSesionFirebaseResponse> IniciarSesionFirebaseAsync(FormularioDePrueba.ServiceReference1.IniciarSesionFirebaseRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://Intec/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/IngresarUsuario", ReplyAction="*")]
        FormularioDePrueba.ServiceReference1.IngresarUsuarioResponse IngresarUsuario(FormularioDePrueba.ServiceReference1.IngresarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/IngresarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.IngresarUsuarioResponse> IngresarUsuarioAsync(FormularioDePrueba.ServiceReference1.IngresarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres http://Intec/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/ObtenerUsuario", ReplyAction="*")]
        FormularioDePrueba.ServiceReference1.ObtenerUsuarioResponse ObtenerUsuario(FormularioDePrueba.ServiceReference1.ObtenerUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/ObtenerUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.ObtenerUsuarioResponse> ObtenerUsuarioAsync(FormularioDePrueba.ServiceReference1.ObtenerUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://Intec/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/ActualizarUsuario", ReplyAction="*")]
        FormularioDePrueba.ServiceReference1.ActualizarUsuarioResponse ActualizarUsuario(FormularioDePrueba.ServiceReference1.ActualizarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/ActualizarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.ActualizarUsuarioResponse> ActualizarUsuarioAsync(FormularioDePrueba.ServiceReference1.ActualizarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento producto del espacio de nombres http://Intec/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/CrearProducto", ReplyAction="*")]
        FormularioDePrueba.ServiceReference1.CrearProductoResponse CrearProducto(FormularioDePrueba.ServiceReference1.CrearProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/CrearProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.CrearProductoResponse> CrearProductoAsync(FormularioDePrueba.ServiceReference1.CrearProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ComandoProductosResult del espacio de nombres http://Intec/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/ComandoProductos", ReplyAction="*")]
        FormularioDePrueba.ServiceReference1.ComandoProductosResponse ComandoProductos(FormularioDePrueba.ServiceReference1.ComandoProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/ComandoProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.ComandoProductosResponse> ComandoProductosAsync(FormularioDePrueba.ServiceReference1.ComandoProductosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento producto del espacio de nombres http://Intec/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/ActualizarProducto", ReplyAction="*")]
        FormularioDePrueba.ServiceReference1.ActualizarProductoResponse ActualizarProducto(FormularioDePrueba.ServiceReference1.ActualizarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/ActualizarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.ActualizarProductoResponse> ActualizarProductoAsync(FormularioDePrueba.ServiceReference1.ActualizarProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento marca del espacio de nombres http://Intec/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/AgregarMarca", ReplyAction="*")]
        FormularioDePrueba.ServiceReference1.AgregarMarcaResponse AgregarMarca(FormularioDePrueba.ServiceReference1.AgregarMarcaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/AgregarMarca", ReplyAction="*")]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.AgregarMarcaResponse> AgregarMarcaAsync(FormularioDePrueba.ServiceReference1.AgregarMarcaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerMarcaResult del espacio de nombres http://Intec/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/ObtenerMarca", ReplyAction="*")]
        FormularioDePrueba.ServiceReference1.ObtenerMarcaResponse ObtenerMarca(FormularioDePrueba.ServiceReference1.ObtenerMarcaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/ObtenerMarca", ReplyAction="*")]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.ObtenerMarcaResponse> ObtenerMarcaAsync(FormularioDePrueba.ServiceReference1.ObtenerMarcaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento categoria del espacio de nombres http://Intec/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/AgregarCategoria", ReplyAction="*")]
        FormularioDePrueba.ServiceReference1.AgregarCategoriaResponse AgregarCategoria(FormularioDePrueba.ServiceReference1.AgregarCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/AgregarCategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.AgregarCategoriaResponse> AgregarCategoriaAsync(FormularioDePrueba.ServiceReference1.AgregarCategoriaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento archivoB del espacio de nombres http://Intec/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/SubirImagen", ReplyAction="*")]
        FormularioDePrueba.ServiceReference1.SubirImagenResponse SubirImagen(FormularioDePrueba.ServiceReference1.SubirImagenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Intec/SubirImagen", ReplyAction="*")]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.SubirImagenResponse> SubirImagenAsync(FormularioDePrueba.ServiceReference1.SubirImagenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarUsuarioFirebaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarUsuarioFirebase", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.EliminarUsuarioFirebaseRequestBody Body;
        
        public EliminarUsuarioFirebaseRequest() {
        }
        
        public EliminarUsuarioFirebaseRequest(FormularioDePrueba.ServiceReference1.EliminarUsuarioFirebaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class EliminarUsuarioFirebaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        public EliminarUsuarioFirebaseRequestBody() {
        }
        
        public EliminarUsuarioFirebaseRequestBody(string email, string contrasena) {
            this.email = email;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarUsuarioFirebaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarUsuarioFirebaseResponse", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.EliminarUsuarioFirebaseResponseBody Body;
        
        public EliminarUsuarioFirebaseResponse() {
        }
        
        public EliminarUsuarioFirebaseResponse(FormularioDePrueba.ServiceReference1.EliminarUsuarioFirebaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class EliminarUsuarioFirebaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EliminarUsuarioFirebaseResult;
        
        public EliminarUsuarioFirebaseResponseBody() {
        }
        
        public EliminarUsuarioFirebaseResponseBody(bool EliminarUsuarioFirebaseResult) {
            this.EliminarUsuarioFirebaseResult = EliminarUsuarioFirebaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IniciarSesionFirebaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IniciarSesionFirebase", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.IniciarSesionFirebaseRequestBody Body;
        
        public IniciarSesionFirebaseRequest() {
        }
        
        public IniciarSesionFirebaseRequest(FormularioDePrueba.ServiceReference1.IniciarSesionFirebaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class IniciarSesionFirebaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        public IniciarSesionFirebaseRequestBody() {
        }
        
        public IniciarSesionFirebaseRequestBody(string email, string contrasena) {
            this.email = email;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IniciarSesionFirebaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IniciarSesionFirebaseResponse", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.IniciarSesionFirebaseResponseBody Body;
        
        public IniciarSesionFirebaseResponse() {
        }
        
        public IniciarSesionFirebaseResponse(FormularioDePrueba.ServiceReference1.IniciarSesionFirebaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class IniciarSesionFirebaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IniciarSesionFirebaseResult;
        
        public IniciarSesionFirebaseResponseBody() {
        }
        
        public IniciarSesionFirebaseResponseBody(string IniciarSesionFirebaseResult) {
            this.IniciarSesionFirebaseResult = IniciarSesionFirebaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresarUsuario", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.IngresarUsuarioRequestBody Body;
        
        public IngresarUsuarioRequest() {
        }
        
        public IngresarUsuarioRequest(FormularioDePrueba.ServiceReference1.IngresarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class IngresarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FormularioDePrueba.ServiceReference1.Usuario user;
        
        public IngresarUsuarioRequestBody() {
        }
        
        public IngresarUsuarioRequestBody(FormularioDePrueba.ServiceReference1.Usuario user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresarUsuarioResponse", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.IngresarUsuarioResponseBody Body;
        
        public IngresarUsuarioResponse() {
        }
        
        public IngresarUsuarioResponse(FormularioDePrueba.ServiceReference1.IngresarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class IngresarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IngresarUsuarioResult;
        
        public IngresarUsuarioResponseBody() {
        }
        
        public IngresarUsuarioResponseBody(bool IngresarUsuarioResult) {
            this.IngresarUsuarioResult = IngresarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerUsuario", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.ObtenerUsuarioRequestBody Body;
        
        public ObtenerUsuarioRequest() {
        }
        
        public ObtenerUsuarioRequest(FormularioDePrueba.ServiceReference1.ObtenerUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class ObtenerUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        public ObtenerUsuarioRequestBody() {
        }
        
        public ObtenerUsuarioRequestBody(string Usuario) {
            this.Usuario = Usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerUsuarioResponse", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.ObtenerUsuarioResponseBody Body;
        
        public ObtenerUsuarioResponse() {
        }
        
        public ObtenerUsuarioResponse(FormularioDePrueba.ServiceReference1.ObtenerUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class ObtenerUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerUsuarioResult;
        
        public ObtenerUsuarioResponseBody() {
        }
        
        public ObtenerUsuarioResponseBody(string ObtenerUsuarioResult) {
            this.ObtenerUsuarioResult = ObtenerUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarUsuario", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.ActualizarUsuarioRequestBody Body;
        
        public ActualizarUsuarioRequest() {
        }
        
        public ActualizarUsuarioRequest(FormularioDePrueba.ServiceReference1.ActualizarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class ActualizarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FormularioDePrueba.ServiceReference1.Usuario user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CorreoAnterior;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UsuaioAnterior;
        
        public ActualizarUsuarioRequestBody() {
        }
        
        public ActualizarUsuarioRequestBody(FormularioDePrueba.ServiceReference1.Usuario user, string CorreoAnterior, string UsuaioAnterior) {
            this.user = user;
            this.CorreoAnterior = CorreoAnterior;
            this.UsuaioAnterior = UsuaioAnterior;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarUsuarioResponse", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.ActualizarUsuarioResponseBody Body;
        
        public ActualizarUsuarioResponse() {
        }
        
        public ActualizarUsuarioResponse(FormularioDePrueba.ServiceReference1.ActualizarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class ActualizarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarUsuarioResult;
        
        public ActualizarUsuarioResponseBody() {
        }
        
        public ActualizarUsuarioResponseBody(bool ActualizarUsuarioResult) {
            this.ActualizarUsuarioResult = ActualizarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearProducto", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.CrearProductoRequestBody Body;
        
        public CrearProductoRequest() {
        }
        
        public CrearProductoRequest(FormularioDePrueba.ServiceReference1.CrearProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class CrearProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FormularioDePrueba.ServiceReference1.Producto producto;
        
        public CrearProductoRequestBody() {
        }
        
        public CrearProductoRequestBody(FormularioDePrueba.ServiceReference1.Producto producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearProductoResponse", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.CrearProductoResponseBody Body;
        
        public CrearProductoResponse() {
        }
        
        public CrearProductoResponse(FormularioDePrueba.ServiceReference1.CrearProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class CrearProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CrearProductoResult;
        
        public CrearProductoResponseBody() {
        }
        
        public CrearProductoResponseBody(bool CrearProductoResult) {
            this.CrearProductoResult = CrearProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComandoProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComandoProductos", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.ComandoProductosRequestBody Body;
        
        public ComandoProductosRequest() {
        }
        
        public ComandoProductosRequest(FormularioDePrueba.ServiceReference1.ComandoProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class ComandoProductosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Orden;
        
        public ComandoProductosRequestBody() {
        }
        
        public ComandoProductosRequestBody(int Orden) {
            this.Orden = Orden;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComandoProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComandoProductosResponse", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.ComandoProductosResponseBody Body;
        
        public ComandoProductosResponse() {
        }
        
        public ComandoProductosResponse(FormularioDePrueba.ServiceReference1.ComandoProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class ComandoProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ComandoProductosResult;
        
        public ComandoProductosResponseBody() {
        }
        
        public ComandoProductosResponseBody(string ComandoProductosResult) {
            this.ComandoProductosResult = ComandoProductosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarProducto", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.ActualizarProductoRequestBody Body;
        
        public ActualizarProductoRequest() {
        }
        
        public ActualizarProductoRequest(FormularioDePrueba.ServiceReference1.ActualizarProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class ActualizarProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FormularioDePrueba.ServiceReference1.Producto producto;
        
        public ActualizarProductoRequestBody() {
        }
        
        public ActualizarProductoRequestBody(FormularioDePrueba.ServiceReference1.Producto producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarProductoResponse", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.ActualizarProductoResponseBody Body;
        
        public ActualizarProductoResponse() {
        }
        
        public ActualizarProductoResponse(FormularioDePrueba.ServiceReference1.ActualizarProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class ActualizarProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarProductoResult;
        
        public ActualizarProductoResponseBody() {
        }
        
        public ActualizarProductoResponseBody(bool ActualizarProductoResult) {
            this.ActualizarProductoResult = ActualizarProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarMarcaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarMarca", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.AgregarMarcaRequestBody Body;
        
        public AgregarMarcaRequest() {
        }
        
        public AgregarMarcaRequest(FormularioDePrueba.ServiceReference1.AgregarMarcaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class AgregarMarcaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FormularioDePrueba.ServiceReference1.Marca marca;
        
        public AgregarMarcaRequestBody() {
        }
        
        public AgregarMarcaRequestBody(FormularioDePrueba.ServiceReference1.Marca marca) {
            this.marca = marca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarMarcaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarMarcaResponse", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.AgregarMarcaResponseBody Body;
        
        public AgregarMarcaResponse() {
        }
        
        public AgregarMarcaResponse(FormularioDePrueba.ServiceReference1.AgregarMarcaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class AgregarMarcaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AgregarMarcaResult;
        
        public AgregarMarcaResponseBody() {
        }
        
        public AgregarMarcaResponseBody(bool AgregarMarcaResult) {
            this.AgregarMarcaResult = AgregarMarcaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerMarcaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerMarca", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.ObtenerMarcaRequestBody Body;
        
        public ObtenerMarcaRequest() {
        }
        
        public ObtenerMarcaRequest(FormularioDePrueba.ServiceReference1.ObtenerMarcaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerMarcaRequestBody {
        
        public ObtenerMarcaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerMarcaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerMarcaResponse", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.ObtenerMarcaResponseBody Body;
        
        public ObtenerMarcaResponse() {
        }
        
        public ObtenerMarcaResponse(FormularioDePrueba.ServiceReference1.ObtenerMarcaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class ObtenerMarcaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerMarcaResult;
        
        public ObtenerMarcaResponseBody() {
        }
        
        public ObtenerMarcaResponseBody(string ObtenerMarcaResult) {
            this.ObtenerMarcaResult = ObtenerMarcaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarCategoria", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.AgregarCategoriaRequestBody Body;
        
        public AgregarCategoriaRequest() {
        }
        
        public AgregarCategoriaRequest(FormularioDePrueba.ServiceReference1.AgregarCategoriaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class AgregarCategoriaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FormularioDePrueba.ServiceReference1.Categoria categoria;
        
        public AgregarCategoriaRequestBody() {
        }
        
        public AgregarCategoriaRequestBody(FormularioDePrueba.ServiceReference1.Categoria categoria) {
            this.categoria = categoria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarCategoriaResponse", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.AgregarCategoriaResponseBody Body;
        
        public AgregarCategoriaResponse() {
        }
        
        public AgregarCategoriaResponse(FormularioDePrueba.ServiceReference1.AgregarCategoriaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class AgregarCategoriaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AgregarCategoriaResult;
        
        public AgregarCategoriaResponseBody() {
        }
        
        public AgregarCategoriaResponseBody(bool AgregarCategoriaResult) {
            this.AgregarCategoriaResult = AgregarCategoriaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubirImagenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubirImagen", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.SubirImagenRequestBody Body;
        
        public SubirImagenRequest() {
        }
        
        public SubirImagenRequest(FormularioDePrueba.ServiceReference1.SubirImagenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class SubirImagenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orden;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] archivoB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombre;
        
        public SubirImagenRequestBody() {
        }
        
        public SubirImagenRequestBody(int orden, byte[] archivoB, string nombre) {
            this.orden = orden;
            this.archivoB = archivoB;
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubirImagenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubirImagenResponse", Namespace="http://Intec/", Order=0)]
        public FormularioDePrueba.ServiceReference1.SubirImagenResponseBody Body;
        
        public SubirImagenResponse() {
        }
        
        public SubirImagenResponse(FormularioDePrueba.ServiceReference1.SubirImagenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Intec/")]
    public partial class SubirImagenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubirImagenResult;
        
        public SubirImagenResponseBody() {
        }
        
        public SubirImagenResponseBody(string SubirImagenResult) {
            this.SubirImagenResult = SubirImagenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioASoapChannel : FormularioDePrueba.ServiceReference1.ServicioASoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioASoapClient : System.ServiceModel.ClientBase<FormularioDePrueba.ServiceReference1.ServicioASoap>, FormularioDePrueba.ServiceReference1.ServicioASoap {
        
        public ServicioASoapClient() {
        }
        
        public ServicioASoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioASoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioASoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioASoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormularioDePrueba.ServiceReference1.EliminarUsuarioFirebaseResponse FormularioDePrueba.ServiceReference1.ServicioASoap.EliminarUsuarioFirebase(FormularioDePrueba.ServiceReference1.EliminarUsuarioFirebaseRequest request) {
            return base.Channel.EliminarUsuarioFirebase(request);
        }
        
        public bool EliminarUsuarioFirebase(string email, string contrasena) {
            FormularioDePrueba.ServiceReference1.EliminarUsuarioFirebaseRequest inValue = new FormularioDePrueba.ServiceReference1.EliminarUsuarioFirebaseRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.EliminarUsuarioFirebaseRequestBody();
            inValue.Body.email = email;
            inValue.Body.contrasena = contrasena;
            FormularioDePrueba.ServiceReference1.EliminarUsuarioFirebaseResponse retVal = ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).EliminarUsuarioFirebase(inValue);
            return retVal.Body.EliminarUsuarioFirebaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.EliminarUsuarioFirebaseResponse> FormularioDePrueba.ServiceReference1.ServicioASoap.EliminarUsuarioFirebaseAsync(FormularioDePrueba.ServiceReference1.EliminarUsuarioFirebaseRequest request) {
            return base.Channel.EliminarUsuarioFirebaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.EliminarUsuarioFirebaseResponse> EliminarUsuarioFirebaseAsync(string email, string contrasena) {
            FormularioDePrueba.ServiceReference1.EliminarUsuarioFirebaseRequest inValue = new FormularioDePrueba.ServiceReference1.EliminarUsuarioFirebaseRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.EliminarUsuarioFirebaseRequestBody();
            inValue.Body.email = email;
            inValue.Body.contrasena = contrasena;
            return ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).EliminarUsuarioFirebaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormularioDePrueba.ServiceReference1.IniciarSesionFirebaseResponse FormularioDePrueba.ServiceReference1.ServicioASoap.IniciarSesionFirebase(FormularioDePrueba.ServiceReference1.IniciarSesionFirebaseRequest request) {
            return base.Channel.IniciarSesionFirebase(request);
        }
        
        public string IniciarSesionFirebase(string email, string contrasena) {
            FormularioDePrueba.ServiceReference1.IniciarSesionFirebaseRequest inValue = new FormularioDePrueba.ServiceReference1.IniciarSesionFirebaseRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.IniciarSesionFirebaseRequestBody();
            inValue.Body.email = email;
            inValue.Body.contrasena = contrasena;
            FormularioDePrueba.ServiceReference1.IniciarSesionFirebaseResponse retVal = ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).IniciarSesionFirebase(inValue);
            return retVal.Body.IniciarSesionFirebaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.IniciarSesionFirebaseResponse> FormularioDePrueba.ServiceReference1.ServicioASoap.IniciarSesionFirebaseAsync(FormularioDePrueba.ServiceReference1.IniciarSesionFirebaseRequest request) {
            return base.Channel.IniciarSesionFirebaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.IniciarSesionFirebaseResponse> IniciarSesionFirebaseAsync(string email, string contrasena) {
            FormularioDePrueba.ServiceReference1.IniciarSesionFirebaseRequest inValue = new FormularioDePrueba.ServiceReference1.IniciarSesionFirebaseRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.IniciarSesionFirebaseRequestBody();
            inValue.Body.email = email;
            inValue.Body.contrasena = contrasena;
            return ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).IniciarSesionFirebaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormularioDePrueba.ServiceReference1.IngresarUsuarioResponse FormularioDePrueba.ServiceReference1.ServicioASoap.IngresarUsuario(FormularioDePrueba.ServiceReference1.IngresarUsuarioRequest request) {
            return base.Channel.IngresarUsuario(request);
        }
        
        public bool IngresarUsuario(FormularioDePrueba.ServiceReference1.Usuario user) {
            FormularioDePrueba.ServiceReference1.IngresarUsuarioRequest inValue = new FormularioDePrueba.ServiceReference1.IngresarUsuarioRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.IngresarUsuarioRequestBody();
            inValue.Body.user = user;
            FormularioDePrueba.ServiceReference1.IngresarUsuarioResponse retVal = ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).IngresarUsuario(inValue);
            return retVal.Body.IngresarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.IngresarUsuarioResponse> FormularioDePrueba.ServiceReference1.ServicioASoap.IngresarUsuarioAsync(FormularioDePrueba.ServiceReference1.IngresarUsuarioRequest request) {
            return base.Channel.IngresarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.IngresarUsuarioResponse> IngresarUsuarioAsync(FormularioDePrueba.ServiceReference1.Usuario user) {
            FormularioDePrueba.ServiceReference1.IngresarUsuarioRequest inValue = new FormularioDePrueba.ServiceReference1.IngresarUsuarioRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.IngresarUsuarioRequestBody();
            inValue.Body.user = user;
            return ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).IngresarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormularioDePrueba.ServiceReference1.ObtenerUsuarioResponse FormularioDePrueba.ServiceReference1.ServicioASoap.ObtenerUsuario(FormularioDePrueba.ServiceReference1.ObtenerUsuarioRequest request) {
            return base.Channel.ObtenerUsuario(request);
        }
        
        public string ObtenerUsuario(string Usuario) {
            FormularioDePrueba.ServiceReference1.ObtenerUsuarioRequest inValue = new FormularioDePrueba.ServiceReference1.ObtenerUsuarioRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.ObtenerUsuarioRequestBody();
            inValue.Body.Usuario = Usuario;
            FormularioDePrueba.ServiceReference1.ObtenerUsuarioResponse retVal = ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).ObtenerUsuario(inValue);
            return retVal.Body.ObtenerUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.ObtenerUsuarioResponse> FormularioDePrueba.ServiceReference1.ServicioASoap.ObtenerUsuarioAsync(FormularioDePrueba.ServiceReference1.ObtenerUsuarioRequest request) {
            return base.Channel.ObtenerUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.ObtenerUsuarioResponse> ObtenerUsuarioAsync(string Usuario) {
            FormularioDePrueba.ServiceReference1.ObtenerUsuarioRequest inValue = new FormularioDePrueba.ServiceReference1.ObtenerUsuarioRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.ObtenerUsuarioRequestBody();
            inValue.Body.Usuario = Usuario;
            return ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).ObtenerUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormularioDePrueba.ServiceReference1.ActualizarUsuarioResponse FormularioDePrueba.ServiceReference1.ServicioASoap.ActualizarUsuario(FormularioDePrueba.ServiceReference1.ActualizarUsuarioRequest request) {
            return base.Channel.ActualizarUsuario(request);
        }
        
        public bool ActualizarUsuario(FormularioDePrueba.ServiceReference1.Usuario user, string CorreoAnterior, string UsuaioAnterior) {
            FormularioDePrueba.ServiceReference1.ActualizarUsuarioRequest inValue = new FormularioDePrueba.ServiceReference1.ActualizarUsuarioRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.ActualizarUsuarioRequestBody();
            inValue.Body.user = user;
            inValue.Body.CorreoAnterior = CorreoAnterior;
            inValue.Body.UsuaioAnterior = UsuaioAnterior;
            FormularioDePrueba.ServiceReference1.ActualizarUsuarioResponse retVal = ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).ActualizarUsuario(inValue);
            return retVal.Body.ActualizarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.ActualizarUsuarioResponse> FormularioDePrueba.ServiceReference1.ServicioASoap.ActualizarUsuarioAsync(FormularioDePrueba.ServiceReference1.ActualizarUsuarioRequest request) {
            return base.Channel.ActualizarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.ActualizarUsuarioResponse> ActualizarUsuarioAsync(FormularioDePrueba.ServiceReference1.Usuario user, string CorreoAnterior, string UsuaioAnterior) {
            FormularioDePrueba.ServiceReference1.ActualizarUsuarioRequest inValue = new FormularioDePrueba.ServiceReference1.ActualizarUsuarioRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.ActualizarUsuarioRequestBody();
            inValue.Body.user = user;
            inValue.Body.CorreoAnterior = CorreoAnterior;
            inValue.Body.UsuaioAnterior = UsuaioAnterior;
            return ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).ActualizarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormularioDePrueba.ServiceReference1.CrearProductoResponse FormularioDePrueba.ServiceReference1.ServicioASoap.CrearProducto(FormularioDePrueba.ServiceReference1.CrearProductoRequest request) {
            return base.Channel.CrearProducto(request);
        }
        
        public bool CrearProducto(FormularioDePrueba.ServiceReference1.Producto producto) {
            FormularioDePrueba.ServiceReference1.CrearProductoRequest inValue = new FormularioDePrueba.ServiceReference1.CrearProductoRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.CrearProductoRequestBody();
            inValue.Body.producto = producto;
            FormularioDePrueba.ServiceReference1.CrearProductoResponse retVal = ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).CrearProducto(inValue);
            return retVal.Body.CrearProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.CrearProductoResponse> FormularioDePrueba.ServiceReference1.ServicioASoap.CrearProductoAsync(FormularioDePrueba.ServiceReference1.CrearProductoRequest request) {
            return base.Channel.CrearProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.CrearProductoResponse> CrearProductoAsync(FormularioDePrueba.ServiceReference1.Producto producto) {
            FormularioDePrueba.ServiceReference1.CrearProductoRequest inValue = new FormularioDePrueba.ServiceReference1.CrearProductoRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.CrearProductoRequestBody();
            inValue.Body.producto = producto;
            return ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).CrearProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormularioDePrueba.ServiceReference1.ComandoProductosResponse FormularioDePrueba.ServiceReference1.ServicioASoap.ComandoProductos(FormularioDePrueba.ServiceReference1.ComandoProductosRequest request) {
            return base.Channel.ComandoProductos(request);
        }
        
        public string ComandoProductos(int Orden) {
            FormularioDePrueba.ServiceReference1.ComandoProductosRequest inValue = new FormularioDePrueba.ServiceReference1.ComandoProductosRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.ComandoProductosRequestBody();
            inValue.Body.Orden = Orden;
            FormularioDePrueba.ServiceReference1.ComandoProductosResponse retVal = ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).ComandoProductos(inValue);
            return retVal.Body.ComandoProductosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.ComandoProductosResponse> FormularioDePrueba.ServiceReference1.ServicioASoap.ComandoProductosAsync(FormularioDePrueba.ServiceReference1.ComandoProductosRequest request) {
            return base.Channel.ComandoProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.ComandoProductosResponse> ComandoProductosAsync(int Orden) {
            FormularioDePrueba.ServiceReference1.ComandoProductosRequest inValue = new FormularioDePrueba.ServiceReference1.ComandoProductosRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.ComandoProductosRequestBody();
            inValue.Body.Orden = Orden;
            return ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).ComandoProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormularioDePrueba.ServiceReference1.ActualizarProductoResponse FormularioDePrueba.ServiceReference1.ServicioASoap.ActualizarProducto(FormularioDePrueba.ServiceReference1.ActualizarProductoRequest request) {
            return base.Channel.ActualizarProducto(request);
        }
        
        public bool ActualizarProducto(FormularioDePrueba.ServiceReference1.Producto producto) {
            FormularioDePrueba.ServiceReference1.ActualizarProductoRequest inValue = new FormularioDePrueba.ServiceReference1.ActualizarProductoRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.ActualizarProductoRequestBody();
            inValue.Body.producto = producto;
            FormularioDePrueba.ServiceReference1.ActualizarProductoResponse retVal = ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).ActualizarProducto(inValue);
            return retVal.Body.ActualizarProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.ActualizarProductoResponse> FormularioDePrueba.ServiceReference1.ServicioASoap.ActualizarProductoAsync(FormularioDePrueba.ServiceReference1.ActualizarProductoRequest request) {
            return base.Channel.ActualizarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.ActualizarProductoResponse> ActualizarProductoAsync(FormularioDePrueba.ServiceReference1.Producto producto) {
            FormularioDePrueba.ServiceReference1.ActualizarProductoRequest inValue = new FormularioDePrueba.ServiceReference1.ActualizarProductoRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.ActualizarProductoRequestBody();
            inValue.Body.producto = producto;
            return ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).ActualizarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormularioDePrueba.ServiceReference1.AgregarMarcaResponse FormularioDePrueba.ServiceReference1.ServicioASoap.AgregarMarca(FormularioDePrueba.ServiceReference1.AgregarMarcaRequest request) {
            return base.Channel.AgregarMarca(request);
        }
        
        public bool AgregarMarca(FormularioDePrueba.ServiceReference1.Marca marca) {
            FormularioDePrueba.ServiceReference1.AgregarMarcaRequest inValue = new FormularioDePrueba.ServiceReference1.AgregarMarcaRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.AgregarMarcaRequestBody();
            inValue.Body.marca = marca;
            FormularioDePrueba.ServiceReference1.AgregarMarcaResponse retVal = ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).AgregarMarca(inValue);
            return retVal.Body.AgregarMarcaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.AgregarMarcaResponse> FormularioDePrueba.ServiceReference1.ServicioASoap.AgregarMarcaAsync(FormularioDePrueba.ServiceReference1.AgregarMarcaRequest request) {
            return base.Channel.AgregarMarcaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.AgregarMarcaResponse> AgregarMarcaAsync(FormularioDePrueba.ServiceReference1.Marca marca) {
            FormularioDePrueba.ServiceReference1.AgregarMarcaRequest inValue = new FormularioDePrueba.ServiceReference1.AgregarMarcaRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.AgregarMarcaRequestBody();
            inValue.Body.marca = marca;
            return ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).AgregarMarcaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormularioDePrueba.ServiceReference1.ObtenerMarcaResponse FormularioDePrueba.ServiceReference1.ServicioASoap.ObtenerMarca(FormularioDePrueba.ServiceReference1.ObtenerMarcaRequest request) {
            return base.Channel.ObtenerMarca(request);
        }
        
        public string ObtenerMarca() {
            FormularioDePrueba.ServiceReference1.ObtenerMarcaRequest inValue = new FormularioDePrueba.ServiceReference1.ObtenerMarcaRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.ObtenerMarcaRequestBody();
            FormularioDePrueba.ServiceReference1.ObtenerMarcaResponse retVal = ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).ObtenerMarca(inValue);
            return retVal.Body.ObtenerMarcaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.ObtenerMarcaResponse> FormularioDePrueba.ServiceReference1.ServicioASoap.ObtenerMarcaAsync(FormularioDePrueba.ServiceReference1.ObtenerMarcaRequest request) {
            return base.Channel.ObtenerMarcaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.ObtenerMarcaResponse> ObtenerMarcaAsync() {
            FormularioDePrueba.ServiceReference1.ObtenerMarcaRequest inValue = new FormularioDePrueba.ServiceReference1.ObtenerMarcaRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.ObtenerMarcaRequestBody();
            return ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).ObtenerMarcaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormularioDePrueba.ServiceReference1.AgregarCategoriaResponse FormularioDePrueba.ServiceReference1.ServicioASoap.AgregarCategoria(FormularioDePrueba.ServiceReference1.AgregarCategoriaRequest request) {
            return base.Channel.AgregarCategoria(request);
        }
        
        public bool AgregarCategoria(FormularioDePrueba.ServiceReference1.Categoria categoria) {
            FormularioDePrueba.ServiceReference1.AgregarCategoriaRequest inValue = new FormularioDePrueba.ServiceReference1.AgregarCategoriaRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.AgregarCategoriaRequestBody();
            inValue.Body.categoria = categoria;
            FormularioDePrueba.ServiceReference1.AgregarCategoriaResponse retVal = ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).AgregarCategoria(inValue);
            return retVal.Body.AgregarCategoriaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.AgregarCategoriaResponse> FormularioDePrueba.ServiceReference1.ServicioASoap.AgregarCategoriaAsync(FormularioDePrueba.ServiceReference1.AgregarCategoriaRequest request) {
            return base.Channel.AgregarCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.AgregarCategoriaResponse> AgregarCategoriaAsync(FormularioDePrueba.ServiceReference1.Categoria categoria) {
            FormularioDePrueba.ServiceReference1.AgregarCategoriaRequest inValue = new FormularioDePrueba.ServiceReference1.AgregarCategoriaRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.AgregarCategoriaRequestBody();
            inValue.Body.categoria = categoria;
            return ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).AgregarCategoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormularioDePrueba.ServiceReference1.SubirImagenResponse FormularioDePrueba.ServiceReference1.ServicioASoap.SubirImagen(FormularioDePrueba.ServiceReference1.SubirImagenRequest request) {
            return base.Channel.SubirImagen(request);
        }
        
        public string SubirImagen(int orden, byte[] archivoB, string nombre) {
            FormularioDePrueba.ServiceReference1.SubirImagenRequest inValue = new FormularioDePrueba.ServiceReference1.SubirImagenRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.SubirImagenRequestBody();
            inValue.Body.orden = orden;
            inValue.Body.archivoB = archivoB;
            inValue.Body.nombre = nombre;
            FormularioDePrueba.ServiceReference1.SubirImagenResponse retVal = ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).SubirImagen(inValue);
            return retVal.Body.SubirImagenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.SubirImagenResponse> FormularioDePrueba.ServiceReference1.ServicioASoap.SubirImagenAsync(FormularioDePrueba.ServiceReference1.SubirImagenRequest request) {
            return base.Channel.SubirImagenAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormularioDePrueba.ServiceReference1.SubirImagenResponse> SubirImagenAsync(int orden, byte[] archivoB, string nombre) {
            FormularioDePrueba.ServiceReference1.SubirImagenRequest inValue = new FormularioDePrueba.ServiceReference1.SubirImagenRequest();
            inValue.Body = new FormularioDePrueba.ServiceReference1.SubirImagenRequestBody();
            inValue.Body.orden = orden;
            inValue.Body.archivoB = archivoB;
            inValue.Body.nombre = nombre;
            return ((FormularioDePrueba.ServiceReference1.ServicioASoap)(this)).SubirImagenAsync(inValue);
        }
    }
}
