//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caja.ServiceProducto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaField;
        
        private decimal PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Caja.ServiceProducto.Imagenes[] ImágenesField;
        
        private int StockField;
        
        private double calificacionField;
        
        private System.DateTime FechaDeCreacionField;
        
        private System.DateTime FechaUltimaModificacionField;
        
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenPrincipalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Caja.ServiceProducto.Imagenes[] Imágenes {
            get {
                return this.ImágenesField;
            }
            set {
                if ((object.ReferenceEquals(this.ImágenesField, value) != true)) {
                    this.ImágenesField = value;
                    this.RaisePropertyChanged("Imágenes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double calificacion {
            get {
                return this.calificacionField;
            }
            set {
                if ((this.calificacionField.Equals(value) != true)) {
                    this.calificacionField = value;
                    this.RaisePropertyChanged("calificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime FechaDeCreacion {
            get {
                return this.FechaDeCreacionField;
            }
            set {
                if ((this.FechaDeCreacionField.Equals(value) != true)) {
                    this.FechaDeCreacionField = value;
                    this.RaisePropertyChanged("FechaDeCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime FechaUltimaModificacion {
            get {
                return this.FechaUltimaModificacionField;
            }
            set {
                if ((this.FechaUltimaModificacionField.Equals(value) != true)) {
                    this.FechaUltimaModificacionField = value;
                    this.RaisePropertyChanged("FechaUltimaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ImagenPrincipal {
            get {
                return this.ImagenPrincipalField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenPrincipalField, value) != true)) {
                    this.ImagenPrincipalField = value;
                    this.RaisePropertyChanged("ImagenPrincipal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Imagenes", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Imagenes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private int IDPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        private System.DateTime FechaDeAsignacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IDP {
            get {
                return this.IDPField;
            }
            set {
                if ((this.IDPField.Equals(value) != true)) {
                    this.IDPField = value;
                    this.RaisePropertyChanged("IDP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime FechaDeAsignacion {
            get {
                return this.FechaDeAsignacionField;
            }
            set {
                if ((this.FechaDeAsignacionField.Equals(value) != true)) {
                    this.FechaDeAsignacionField = value;
                    this.RaisePropertyChanged("FechaDeAsignacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Task", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Caja.ServiceProducto.TaskOfBoolean))]
    public partial class Task : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskOfBoolean", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TaskOfBoolean : Caja.ServiceProducto.Task {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProducto.ServicioProductoSoap")]
    public interface ServicioProductoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento producto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearProducto", ReplyAction="*")]
        Caja.ServiceProducto.CrearProductoResponse CrearProducto(Caja.ServiceProducto.CrearProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<Caja.ServiceProducto.CrearProductoResponse> CrearProductoAsync(Caja.ServiceProducto.CrearProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Remitente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImagenesProducto", ReplyAction="*")]
        Caja.ServiceProducto.ImagenesProductoResponse ImagenesProducto(Caja.ServiceProducto.ImagenesProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImagenesProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<Caja.ServiceProducto.ImagenesProductoResponse> ImagenesProductoAsync(Caja.ServiceProducto.ImagenesProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProductoExiste", ReplyAction="*")]
        Caja.ServiceProducto.ProductoExisteResponse ProductoExiste(Caja.ServiceProducto.ProductoExisteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProductoExiste", ReplyAction="*")]
        System.Threading.Tasks.Task<Caja.ServiceProducto.ProductoExisteResponse> ProductoExisteAsync(Caja.ServiceProducto.ProductoExisteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Remitente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ComandoProductos", ReplyAction="*")]
        Caja.ServiceProducto.ComandoProductosResponse ComandoProductos(Caja.ServiceProducto.ComandoProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ComandoProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<Caja.ServiceProducto.ComandoProductosResponse> ComandoProductosAsync(Caja.ServiceProducto.ComandoProductosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento producto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarProducto", ReplyAction="*")]
        Caja.ServiceProducto.ActualizarProductoResponse ActualizarProducto(Caja.ServiceProducto.ActualizarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<Caja.ServiceProducto.ActualizarProductoResponse> ActualizarProductoAsync(Caja.ServiceProducto.ActualizarProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Remitente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarProducto", ReplyAction="*")]
        Caja.ServiceProducto.EliminarProductoResponse EliminarProducto(Caja.ServiceProducto.EliminarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<Caja.ServiceProducto.EliminarProductoResponse> EliminarProductoAsync(Caja.ServiceProducto.EliminarProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento imagenes del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarImagenProducto", ReplyAction="*")]
        Caja.ServiceProducto.AgregarImagenProductoResponse AgregarImagenProducto(Caja.ServiceProducto.AgregarImagenProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarImagenProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<Caja.ServiceProducto.AgregarImagenProductoResponse> AgregarImagenProductoAsync(Caja.ServiceProducto.AgregarImagenProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Remitente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerImagenesProducto", ReplyAction="*")]
        Caja.ServiceProducto.ObtenerImagenesProductoResponse ObtenerImagenesProducto(Caja.ServiceProducto.ObtenerImagenesProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerImagenesProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<Caja.ServiceProducto.ObtenerImagenesProductoResponse> ObtenerImagenesProductoAsync(Caja.ServiceProducto.ObtenerImagenesProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NombreImagen del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarImagenP", ReplyAction="*")]
        Caja.ServiceProducto.EliminarImagenPResponse EliminarImagenP(Caja.ServiceProducto.EliminarImagenPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarImagenP", ReplyAction="*")]
        System.Threading.Tasks.Task<Caja.ServiceProducto.EliminarImagenPResponse> EliminarImagenPAsync(Caja.ServiceProducto.EliminarImagenPRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearProducto", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceProducto.CrearProductoRequestBody Body;
        
        public CrearProductoRequest() {
        }
        
        public CrearProductoRequest(Caja.ServiceProducto.CrearProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Caja.ServiceProducto.Producto producto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public CrearProductoRequestBody() {
        }
        
        public CrearProductoRequestBody(Caja.ServiceProducto.Producto producto, string Remitente, int Origen) {
            this.producto = producto;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceProducto.CrearProductoResponseBody Body;
        
        public CrearProductoResponse() {
        }
        
        public CrearProductoResponse(Caja.ServiceProducto.CrearProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CrearProductoResult;
        
        public CrearProductoResponseBody() {
        }
        
        public CrearProductoResponseBody(bool CrearProductoResult) {
            this.CrearProductoResult = CrearProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImagenesProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImagenesProducto", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceProducto.ImagenesProductoRequestBody Body;
        
        public ImagenesProductoRequest() {
        }
        
        public ImagenesProductoRequest(Caja.ServiceProducto.ImagenesProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImagenesProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public ImagenesProductoRequestBody() {
        }
        
        public ImagenesProductoRequestBody(int id, string Remitente, int Origen) {
            this.id = id;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImagenesProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImagenesProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceProducto.ImagenesProductoResponseBody Body;
        
        public ImagenesProductoResponse() {
        }
        
        public ImagenesProductoResponse(Caja.ServiceProducto.ImagenesProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImagenesProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Caja.ServiceProducto.Imagenes[] ImagenesProductoResult;
        
        public ImagenesProductoResponseBody() {
        }
        
        public ImagenesProductoResponseBody(Caja.ServiceProducto.Imagenes[] ImagenesProductoResult) {
            this.ImagenesProductoResult = ImagenesProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProductoExisteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProductoExiste", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceProducto.ProductoExisteRequestBody Body;
        
        public ProductoExisteRequest() {
        }
        
        public ProductoExisteRequest(Caja.ServiceProducto.ProductoExisteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoExisteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public ProductoExisteRequestBody() {
        }
        
        public ProductoExisteRequestBody(string nombre, string Remitente, int Origen) {
            this.nombre = nombre;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProductoExisteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProductoExisteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceProducto.ProductoExisteResponseBody Body;
        
        public ProductoExisteResponse() {
        }
        
        public ProductoExisteResponse(Caja.ServiceProducto.ProductoExisteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductoExisteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ProductoExisteResult;
        
        public ProductoExisteResponseBody() {
        }
        
        public ProductoExisteResponseBody(bool ProductoExisteResult) {
            this.ProductoExisteResult = ProductoExisteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComandoProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComandoProductos", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceProducto.ComandoProductosRequestBody Body;
        
        public ComandoProductosRequest() {
        }
        
        public ComandoProductosRequest(Caja.ServiceProducto.ComandoProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ComandoProductosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Orden;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public ComandoProductosRequestBody() {
        }
        
        public ComandoProductosRequestBody(int Orden, string Remitente, int Origen) {
            this.Orden = Orden;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComandoProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComandoProductosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceProducto.ComandoProductosResponseBody Body;
        
        public ComandoProductosResponse() {
        }
        
        public ComandoProductosResponse(Caja.ServiceProducto.ComandoProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ComandoProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ComandoProductosResult;
        
        public ComandoProductosResponseBody() {
        }
        
        public ComandoProductosResponseBody(string ComandoProductosResult) {
            this.ComandoProductosResult = ComandoProductosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarProducto", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceProducto.ActualizarProductoRequestBody Body;
        
        public ActualizarProductoRequest() {
        }
        
        public ActualizarProductoRequest(Caja.ServiceProducto.ActualizarProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Caja.ServiceProducto.Producto producto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public ActualizarProductoRequestBody() {
        }
        
        public ActualizarProductoRequestBody(Caja.ServiceProducto.Producto producto, string Remitente, int Origen) {
            this.producto = producto;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceProducto.ActualizarProductoResponseBody Body;
        
        public ActualizarProductoResponse() {
        }
        
        public ActualizarProductoResponse(Caja.ServiceProducto.ActualizarProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarProductoResult;
        
        public ActualizarProductoResponseBody() {
        }
        
        public ActualizarProductoResponseBody(bool ActualizarProductoResult) {
            this.ActualizarProductoResult = ActualizarProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarProducto", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceProducto.EliminarProductoRequestBody Body;
        
        public EliminarProductoRequest() {
        }
        
        public EliminarProductoRequest(Caja.ServiceProducto.EliminarProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public EliminarProductoRequestBody() {
        }
        
        public EliminarProductoRequestBody(int Id, string Remitente, int Origen) {
            this.Id = Id;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceProducto.EliminarProductoResponseBody Body;
        
        public EliminarProductoResponse() {
        }
        
        public EliminarProductoResponse(Caja.ServiceProducto.EliminarProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EliminarProductoResult;
        
        public EliminarProductoResponseBody() {
        }
        
        public EliminarProductoResponseBody(bool EliminarProductoResult) {
            this.EliminarProductoResult = EliminarProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarImagenProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarImagenProducto", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceProducto.AgregarImagenProductoRequestBody Body;
        
        public AgregarImagenProductoRequest() {
        }
        
        public AgregarImagenProductoRequest(Caja.ServiceProducto.AgregarImagenProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarImagenProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Caja.ServiceProducto.Imagenes imagenes;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public AgregarImagenProductoRequestBody() {
        }
        
        public AgregarImagenProductoRequestBody(Caja.ServiceProducto.Imagenes imagenes, string Remitente, int Origen) {
            this.imagenes = imagenes;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarImagenProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarImagenProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceProducto.AgregarImagenProductoResponseBody Body;
        
        public AgregarImagenProductoResponse() {
        }
        
        public AgregarImagenProductoResponse(Caja.ServiceProducto.AgregarImagenProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarImagenProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AgregarImagenProductoResult;
        
        public AgregarImagenProductoResponseBody() {
        }
        
        public AgregarImagenProductoResponseBody(bool AgregarImagenProductoResult) {
            this.AgregarImagenProductoResult = AgregarImagenProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerImagenesProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerImagenesProducto", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceProducto.ObtenerImagenesProductoRequestBody Body;
        
        public ObtenerImagenesProductoRequest() {
        }
        
        public ObtenerImagenesProductoRequest(Caja.ServiceProducto.ObtenerImagenesProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerImagenesProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public ObtenerImagenesProductoRequestBody() {
        }
        
        public ObtenerImagenesProductoRequestBody(int ID, string Remitente, int Origen) {
            this.ID = ID;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerImagenesProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerImagenesProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceProducto.ObtenerImagenesProductoResponseBody Body;
        
        public ObtenerImagenesProductoResponse() {
        }
        
        public ObtenerImagenesProductoResponse(Caja.ServiceProducto.ObtenerImagenesProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerImagenesProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerImagenesProductoResult;
        
        public ObtenerImagenesProductoResponseBody() {
        }
        
        public ObtenerImagenesProductoResponseBody(string ObtenerImagenesProductoResult) {
            this.ObtenerImagenesProductoResult = ObtenerImagenesProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarImagenPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarImagenP", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceProducto.EliminarImagenPRequestBody Body;
        
        public EliminarImagenPRequest() {
        }
        
        public EliminarImagenPRequest(Caja.ServiceProducto.EliminarImagenPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarImagenPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NombreImagen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public EliminarImagenPRequestBody() {
        }
        
        public EliminarImagenPRequestBody(string NombreImagen, string Remitente, int Origen) {
            this.NombreImagen = NombreImagen;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarImagenPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarImagenPResponse", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceProducto.EliminarImagenPResponseBody Body;
        
        public EliminarImagenPResponse() {
        }
        
        public EliminarImagenPResponse(Caja.ServiceProducto.EliminarImagenPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarImagenPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Caja.ServiceProducto.TaskOfBoolean EliminarImagenPResult;
        
        public EliminarImagenPResponseBody() {
        }
        
        public EliminarImagenPResponseBody(Caja.ServiceProducto.TaskOfBoolean EliminarImagenPResult) {
            this.EliminarImagenPResult = EliminarImagenPResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioProductoSoapChannel : Caja.ServiceProducto.ServicioProductoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioProductoSoapClient : System.ServiceModel.ClientBase<Caja.ServiceProducto.ServicioProductoSoap>, Caja.ServiceProducto.ServicioProductoSoap {
        
        public ServicioProductoSoapClient() {
        }
        
        public ServicioProductoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioProductoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProductoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProductoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Caja.ServiceProducto.CrearProductoResponse Caja.ServiceProducto.ServicioProductoSoap.CrearProducto(Caja.ServiceProducto.CrearProductoRequest request) {
            return base.Channel.CrearProducto(request);
        }
        
        public bool CrearProducto(Caja.ServiceProducto.Producto producto, string Remitente, int Origen) {
            Caja.ServiceProducto.CrearProductoRequest inValue = new Caja.ServiceProducto.CrearProductoRequest();
            inValue.Body = new Caja.ServiceProducto.CrearProductoRequestBody();
            inValue.Body.producto = producto;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            Caja.ServiceProducto.CrearProductoResponse retVal = ((Caja.ServiceProducto.ServicioProductoSoap)(this)).CrearProducto(inValue);
            return retVal.Body.CrearProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Caja.ServiceProducto.CrearProductoResponse> Caja.ServiceProducto.ServicioProductoSoap.CrearProductoAsync(Caja.ServiceProducto.CrearProductoRequest request) {
            return base.Channel.CrearProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Caja.ServiceProducto.CrearProductoResponse> CrearProductoAsync(Caja.ServiceProducto.Producto producto, string Remitente, int Origen) {
            Caja.ServiceProducto.CrearProductoRequest inValue = new Caja.ServiceProducto.CrearProductoRequest();
            inValue.Body = new Caja.ServiceProducto.CrearProductoRequestBody();
            inValue.Body.producto = producto;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((Caja.ServiceProducto.ServicioProductoSoap)(this)).CrearProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Caja.ServiceProducto.ImagenesProductoResponse Caja.ServiceProducto.ServicioProductoSoap.ImagenesProducto(Caja.ServiceProducto.ImagenesProductoRequest request) {
            return base.Channel.ImagenesProducto(request);
        }
        
        public Caja.ServiceProducto.Imagenes[] ImagenesProducto(int id, string Remitente, int Origen) {
            Caja.ServiceProducto.ImagenesProductoRequest inValue = new Caja.ServiceProducto.ImagenesProductoRequest();
            inValue.Body = new Caja.ServiceProducto.ImagenesProductoRequestBody();
            inValue.Body.id = id;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            Caja.ServiceProducto.ImagenesProductoResponse retVal = ((Caja.ServiceProducto.ServicioProductoSoap)(this)).ImagenesProducto(inValue);
            return retVal.Body.ImagenesProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Caja.ServiceProducto.ImagenesProductoResponse> Caja.ServiceProducto.ServicioProductoSoap.ImagenesProductoAsync(Caja.ServiceProducto.ImagenesProductoRequest request) {
            return base.Channel.ImagenesProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Caja.ServiceProducto.ImagenesProductoResponse> ImagenesProductoAsync(int id, string Remitente, int Origen) {
            Caja.ServiceProducto.ImagenesProductoRequest inValue = new Caja.ServiceProducto.ImagenesProductoRequest();
            inValue.Body = new Caja.ServiceProducto.ImagenesProductoRequestBody();
            inValue.Body.id = id;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((Caja.ServiceProducto.ServicioProductoSoap)(this)).ImagenesProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Caja.ServiceProducto.ProductoExisteResponse Caja.ServiceProducto.ServicioProductoSoap.ProductoExiste(Caja.ServiceProducto.ProductoExisteRequest request) {
            return base.Channel.ProductoExiste(request);
        }
        
        public bool ProductoExiste(string nombre, string Remitente, int Origen) {
            Caja.ServiceProducto.ProductoExisteRequest inValue = new Caja.ServiceProducto.ProductoExisteRequest();
            inValue.Body = new Caja.ServiceProducto.ProductoExisteRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            Caja.ServiceProducto.ProductoExisteResponse retVal = ((Caja.ServiceProducto.ServicioProductoSoap)(this)).ProductoExiste(inValue);
            return retVal.Body.ProductoExisteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Caja.ServiceProducto.ProductoExisteResponse> Caja.ServiceProducto.ServicioProductoSoap.ProductoExisteAsync(Caja.ServiceProducto.ProductoExisteRequest request) {
            return base.Channel.ProductoExisteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Caja.ServiceProducto.ProductoExisteResponse> ProductoExisteAsync(string nombre, string Remitente, int Origen) {
            Caja.ServiceProducto.ProductoExisteRequest inValue = new Caja.ServiceProducto.ProductoExisteRequest();
            inValue.Body = new Caja.ServiceProducto.ProductoExisteRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((Caja.ServiceProducto.ServicioProductoSoap)(this)).ProductoExisteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Caja.ServiceProducto.ComandoProductosResponse Caja.ServiceProducto.ServicioProductoSoap.ComandoProductos(Caja.ServiceProducto.ComandoProductosRequest request) {
            return base.Channel.ComandoProductos(request);
        }
        
        public string ComandoProductos(int Orden, string Remitente, int Origen) {
            Caja.ServiceProducto.ComandoProductosRequest inValue = new Caja.ServiceProducto.ComandoProductosRequest();
            inValue.Body = new Caja.ServiceProducto.ComandoProductosRequestBody();
            inValue.Body.Orden = Orden;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            Caja.ServiceProducto.ComandoProductosResponse retVal = ((Caja.ServiceProducto.ServicioProductoSoap)(this)).ComandoProductos(inValue);
            return retVal.Body.ComandoProductosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Caja.ServiceProducto.ComandoProductosResponse> Caja.ServiceProducto.ServicioProductoSoap.ComandoProductosAsync(Caja.ServiceProducto.ComandoProductosRequest request) {
            return base.Channel.ComandoProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Caja.ServiceProducto.ComandoProductosResponse> ComandoProductosAsync(int Orden, string Remitente, int Origen) {
            Caja.ServiceProducto.ComandoProductosRequest inValue = new Caja.ServiceProducto.ComandoProductosRequest();
            inValue.Body = new Caja.ServiceProducto.ComandoProductosRequestBody();
            inValue.Body.Orden = Orden;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((Caja.ServiceProducto.ServicioProductoSoap)(this)).ComandoProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Caja.ServiceProducto.ActualizarProductoResponse Caja.ServiceProducto.ServicioProductoSoap.ActualizarProducto(Caja.ServiceProducto.ActualizarProductoRequest request) {
            return base.Channel.ActualizarProducto(request);
        }
        
        public bool ActualizarProducto(Caja.ServiceProducto.Producto producto, string Remitente, int Origen) {
            Caja.ServiceProducto.ActualizarProductoRequest inValue = new Caja.ServiceProducto.ActualizarProductoRequest();
            inValue.Body = new Caja.ServiceProducto.ActualizarProductoRequestBody();
            inValue.Body.producto = producto;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            Caja.ServiceProducto.ActualizarProductoResponse retVal = ((Caja.ServiceProducto.ServicioProductoSoap)(this)).ActualizarProducto(inValue);
            return retVal.Body.ActualizarProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Caja.ServiceProducto.ActualizarProductoResponse> Caja.ServiceProducto.ServicioProductoSoap.ActualizarProductoAsync(Caja.ServiceProducto.ActualizarProductoRequest request) {
            return base.Channel.ActualizarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Caja.ServiceProducto.ActualizarProductoResponse> ActualizarProductoAsync(Caja.ServiceProducto.Producto producto, string Remitente, int Origen) {
            Caja.ServiceProducto.ActualizarProductoRequest inValue = new Caja.ServiceProducto.ActualizarProductoRequest();
            inValue.Body = new Caja.ServiceProducto.ActualizarProductoRequestBody();
            inValue.Body.producto = producto;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((Caja.ServiceProducto.ServicioProductoSoap)(this)).ActualizarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Caja.ServiceProducto.EliminarProductoResponse Caja.ServiceProducto.ServicioProductoSoap.EliminarProducto(Caja.ServiceProducto.EliminarProductoRequest request) {
            return base.Channel.EliminarProducto(request);
        }
        
        public bool EliminarProducto(int Id, string Remitente, int Origen) {
            Caja.ServiceProducto.EliminarProductoRequest inValue = new Caja.ServiceProducto.EliminarProductoRequest();
            inValue.Body = new Caja.ServiceProducto.EliminarProductoRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            Caja.ServiceProducto.EliminarProductoResponse retVal = ((Caja.ServiceProducto.ServicioProductoSoap)(this)).EliminarProducto(inValue);
            return retVal.Body.EliminarProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Caja.ServiceProducto.EliminarProductoResponse> Caja.ServiceProducto.ServicioProductoSoap.EliminarProductoAsync(Caja.ServiceProducto.EliminarProductoRequest request) {
            return base.Channel.EliminarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Caja.ServiceProducto.EliminarProductoResponse> EliminarProductoAsync(int Id, string Remitente, int Origen) {
            Caja.ServiceProducto.EliminarProductoRequest inValue = new Caja.ServiceProducto.EliminarProductoRequest();
            inValue.Body = new Caja.ServiceProducto.EliminarProductoRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((Caja.ServiceProducto.ServicioProductoSoap)(this)).EliminarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Caja.ServiceProducto.AgregarImagenProductoResponse Caja.ServiceProducto.ServicioProductoSoap.AgregarImagenProducto(Caja.ServiceProducto.AgregarImagenProductoRequest request) {
            return base.Channel.AgregarImagenProducto(request);
        }
        
        public bool AgregarImagenProducto(Caja.ServiceProducto.Imagenes imagenes, string Remitente, int Origen) {
            Caja.ServiceProducto.AgregarImagenProductoRequest inValue = new Caja.ServiceProducto.AgregarImagenProductoRequest();
            inValue.Body = new Caja.ServiceProducto.AgregarImagenProductoRequestBody();
            inValue.Body.imagenes = imagenes;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            Caja.ServiceProducto.AgregarImagenProductoResponse retVal = ((Caja.ServiceProducto.ServicioProductoSoap)(this)).AgregarImagenProducto(inValue);
            return retVal.Body.AgregarImagenProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Caja.ServiceProducto.AgregarImagenProductoResponse> Caja.ServiceProducto.ServicioProductoSoap.AgregarImagenProductoAsync(Caja.ServiceProducto.AgregarImagenProductoRequest request) {
            return base.Channel.AgregarImagenProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Caja.ServiceProducto.AgregarImagenProductoResponse> AgregarImagenProductoAsync(Caja.ServiceProducto.Imagenes imagenes, string Remitente, int Origen) {
            Caja.ServiceProducto.AgregarImagenProductoRequest inValue = new Caja.ServiceProducto.AgregarImagenProductoRequest();
            inValue.Body = new Caja.ServiceProducto.AgregarImagenProductoRequestBody();
            inValue.Body.imagenes = imagenes;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((Caja.ServiceProducto.ServicioProductoSoap)(this)).AgregarImagenProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Caja.ServiceProducto.ObtenerImagenesProductoResponse Caja.ServiceProducto.ServicioProductoSoap.ObtenerImagenesProducto(Caja.ServiceProducto.ObtenerImagenesProductoRequest request) {
            return base.Channel.ObtenerImagenesProducto(request);
        }
        
        public string ObtenerImagenesProducto(int ID, string Remitente, int Origen) {
            Caja.ServiceProducto.ObtenerImagenesProductoRequest inValue = new Caja.ServiceProducto.ObtenerImagenesProductoRequest();
            inValue.Body = new Caja.ServiceProducto.ObtenerImagenesProductoRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            Caja.ServiceProducto.ObtenerImagenesProductoResponse retVal = ((Caja.ServiceProducto.ServicioProductoSoap)(this)).ObtenerImagenesProducto(inValue);
            return retVal.Body.ObtenerImagenesProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Caja.ServiceProducto.ObtenerImagenesProductoResponse> Caja.ServiceProducto.ServicioProductoSoap.ObtenerImagenesProductoAsync(Caja.ServiceProducto.ObtenerImagenesProductoRequest request) {
            return base.Channel.ObtenerImagenesProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Caja.ServiceProducto.ObtenerImagenesProductoResponse> ObtenerImagenesProductoAsync(int ID, string Remitente, int Origen) {
            Caja.ServiceProducto.ObtenerImagenesProductoRequest inValue = new Caja.ServiceProducto.ObtenerImagenesProductoRequest();
            inValue.Body = new Caja.ServiceProducto.ObtenerImagenesProductoRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((Caja.ServiceProducto.ServicioProductoSoap)(this)).ObtenerImagenesProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Caja.ServiceProducto.EliminarImagenPResponse Caja.ServiceProducto.ServicioProductoSoap.EliminarImagenP(Caja.ServiceProducto.EliminarImagenPRequest request) {
            return base.Channel.EliminarImagenP(request);
        }
        
        public Caja.ServiceProducto.TaskOfBoolean EliminarImagenP(string NombreImagen, string Remitente, int Origen) {
            Caja.ServiceProducto.EliminarImagenPRequest inValue = new Caja.ServiceProducto.EliminarImagenPRequest();
            inValue.Body = new Caja.ServiceProducto.EliminarImagenPRequestBody();
            inValue.Body.NombreImagen = NombreImagen;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            Caja.ServiceProducto.EliminarImagenPResponse retVal = ((Caja.ServiceProducto.ServicioProductoSoap)(this)).EliminarImagenP(inValue);
            return retVal.Body.EliminarImagenPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Caja.ServiceProducto.EliminarImagenPResponse> Caja.ServiceProducto.ServicioProductoSoap.EliminarImagenPAsync(Caja.ServiceProducto.EliminarImagenPRequest request) {
            return base.Channel.EliminarImagenPAsync(request);
        }
        
        public System.Threading.Tasks.Task<Caja.ServiceProducto.EliminarImagenPResponse> EliminarImagenPAsync(string NombreImagen, string Remitente, int Origen) {
            Caja.ServiceProducto.EliminarImagenPRequest inValue = new Caja.ServiceProducto.EliminarImagenPRequest();
            inValue.Body = new Caja.ServiceProducto.EliminarImagenPRequestBody();
            inValue.Body.NombreImagen = NombreImagen;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((Caja.ServiceProducto.ServicioProductoSoap)(this)).EliminarImagenPAsync(inValue);
        }
    }
}
