//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caja.ServiceUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        private int EstadoField;
        
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ImagenUsuario {
            get {
                return this.ImagenUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenUsuarioField, value) != true)) {
                    this.ImagenUsuarioField = value;
                    this.RaisePropertyChanged("ImagenUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUsuario.ServicioUsuarioSoap")]
    public interface ServicioUsuarioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento email del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarUsuarioFirebase", ReplyAction="*")]
        Caja.ServiceUsuario.EliminarUsuarioFirebaseResponse EliminarUsuarioFirebase(Caja.ServiceUsuario.EliminarUsuarioFirebaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarUsuarioFirebase", ReplyAction="*")]
        System.Threading.Tasks.Task<Caja.ServiceUsuario.EliminarUsuarioFirebaseResponse> EliminarUsuarioFirebaseAsync(Caja.ServiceUsuario.EliminarUsuarioFirebaseRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento email del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IniciarSesionFirebase", ReplyAction="*")]
        Caja.ServiceUsuario.IniciarSesionFirebaseResponse IniciarSesionFirebase(Caja.ServiceUsuario.IniciarSesionFirebaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IniciarSesionFirebase", ReplyAction="*")]
        System.Threading.Tasks.Task<Caja.ServiceUsuario.IniciarSesionFirebaseResponse> IniciarSesionFirebaseAsync(Caja.ServiceUsuario.IniciarSesionFirebaseRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IngresarUsuario", ReplyAction="*")]
        Caja.ServiceUsuario.IngresarUsuarioResponse IngresarUsuario(Caja.ServiceUsuario.IngresarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IngresarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<Caja.ServiceUsuario.IngresarUsuarioResponse> IngresarUsuarioAsync(Caja.ServiceUsuario.IngresarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerUsuario", ReplyAction="*")]
        Caja.ServiceUsuario.ObtenerUsuarioResponse ObtenerUsuario(Caja.ServiceUsuario.ObtenerUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<Caja.ServiceUsuario.ObtenerUsuarioResponse> ObtenerUsuarioAsync(Caja.ServiceUsuario.ObtenerUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarUsuario", ReplyAction="*")]
        Caja.ServiceUsuario.ActualizarUsuarioResponse ActualizarUsuario(Caja.ServiceUsuario.ActualizarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<Caja.ServiceUsuario.ActualizarUsuarioResponse> ActualizarUsuarioAsync(Caja.ServiceUsuario.ActualizarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Remitente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarUsuario", ReplyAction="*")]
        Caja.ServiceUsuario.EliminarUsuarioResponse EliminarUsuario(Caja.ServiceUsuario.EliminarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<Caja.ServiceUsuario.EliminarUsuarioResponse> EliminarUsuarioAsync(Caja.ServiceUsuario.EliminarUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarUsuarioFirebaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarUsuarioFirebase", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceUsuario.EliminarUsuarioFirebaseRequestBody Body;
        
        public EliminarUsuarioFirebaseRequest() {
        }
        
        public EliminarUsuarioFirebaseRequest(Caja.ServiceUsuario.EliminarUsuarioFirebaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarUsuarioFirebaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Origen;
        
        public EliminarUsuarioFirebaseRequestBody() {
        }
        
        public EliminarUsuarioFirebaseRequestBody(string email, string contrasena, string Remitente, int Origen) {
            this.email = email;
            this.contrasena = contrasena;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarUsuarioFirebaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarUsuarioFirebaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceUsuario.EliminarUsuarioFirebaseResponseBody Body;
        
        public EliminarUsuarioFirebaseResponse() {
        }
        
        public EliminarUsuarioFirebaseResponse(Caja.ServiceUsuario.EliminarUsuarioFirebaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarUsuarioFirebaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EliminarUsuarioFirebaseResult;
        
        public EliminarUsuarioFirebaseResponseBody() {
        }
        
        public EliminarUsuarioFirebaseResponseBody(bool EliminarUsuarioFirebaseResult) {
            this.EliminarUsuarioFirebaseResult = EliminarUsuarioFirebaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IniciarSesionFirebaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IniciarSesionFirebase", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceUsuario.IniciarSesionFirebaseRequestBody Body;
        
        public IniciarSesionFirebaseRequest() {
        }
        
        public IniciarSesionFirebaseRequest(Caja.ServiceUsuario.IniciarSesionFirebaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IniciarSesionFirebaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Origen;
        
        public IniciarSesionFirebaseRequestBody() {
        }
        
        public IniciarSesionFirebaseRequestBody(string email, string contrasena, string Remitente, int Origen) {
            this.email = email;
            this.contrasena = contrasena;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IniciarSesionFirebaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IniciarSesionFirebaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceUsuario.IniciarSesionFirebaseResponseBody Body;
        
        public IniciarSesionFirebaseResponse() {
        }
        
        public IniciarSesionFirebaseResponse(Caja.ServiceUsuario.IniciarSesionFirebaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IniciarSesionFirebaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IniciarSesionFirebaseResult;
        
        public IniciarSesionFirebaseResponseBody() {
        }
        
        public IniciarSesionFirebaseResponseBody(string IniciarSesionFirebaseResult) {
            this.IniciarSesionFirebaseResult = IniciarSesionFirebaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceUsuario.IngresarUsuarioRequestBody Body;
        
        public IngresarUsuarioRequest() {
        }
        
        public IngresarUsuarioRequest(Caja.ServiceUsuario.IngresarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IngresarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Caja.ServiceUsuario.Usuario user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public IngresarUsuarioRequestBody() {
        }
        
        public IngresarUsuarioRequestBody(Caja.ServiceUsuario.Usuario user, string Remitente, int Origen) {
            this.user = user;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceUsuario.IngresarUsuarioResponseBody Body;
        
        public IngresarUsuarioResponse() {
        }
        
        public IngresarUsuarioResponse(Caja.ServiceUsuario.IngresarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IngresarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IngresarUsuarioResult;
        
        public IngresarUsuarioResponseBody() {
        }
        
        public IngresarUsuarioResponseBody(bool IngresarUsuarioResult) {
            this.IngresarUsuarioResult = IngresarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerUsuario", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceUsuario.ObtenerUsuarioRequestBody Body;
        
        public ObtenerUsuarioRequest() {
        }
        
        public ObtenerUsuarioRequest(Caja.ServiceUsuario.ObtenerUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public ObtenerUsuarioRequestBody() {
        }
        
        public ObtenerUsuarioRequestBody(string Usuario, string Remitente, int Origen) {
            this.Usuario = Usuario;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceUsuario.ObtenerUsuarioResponseBody Body;
        
        public ObtenerUsuarioResponse() {
        }
        
        public ObtenerUsuarioResponse(Caja.ServiceUsuario.ObtenerUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerUsuarioResult;
        
        public ObtenerUsuarioResponseBody() {
        }
        
        public ObtenerUsuarioResponseBody(string ObtenerUsuarioResult) {
            this.ObtenerUsuarioResult = ObtenerUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceUsuario.ActualizarUsuarioRequestBody Body;
        
        public ActualizarUsuarioRequest() {
        }
        
        public ActualizarUsuarioRequest(Caja.ServiceUsuario.ActualizarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Caja.ServiceUsuario.Usuario user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CorreoAnterior;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UsuaioAnterior;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Origen;
        
        public ActualizarUsuarioRequestBody() {
        }
        
        public ActualizarUsuarioRequestBody(Caja.ServiceUsuario.Usuario user, string CorreoAnterior, string UsuaioAnterior, string Remitente, int Origen) {
            this.user = user;
            this.CorreoAnterior = CorreoAnterior;
            this.UsuaioAnterior = UsuaioAnterior;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceUsuario.ActualizarUsuarioResponseBody Body;
        
        public ActualizarUsuarioResponse() {
        }
        
        public ActualizarUsuarioResponse(Caja.ServiceUsuario.ActualizarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarUsuarioResult;
        
        public ActualizarUsuarioResponseBody() {
        }
        
        public ActualizarUsuarioResponseBody(bool ActualizarUsuarioResult) {
            this.ActualizarUsuarioResult = ActualizarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceUsuario.EliminarUsuarioRequestBody Body;
        
        public EliminarUsuarioRequest() {
        }
        
        public EliminarUsuarioRequest(Caja.ServiceUsuario.EliminarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Remitente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Origen;
        
        public EliminarUsuarioRequestBody() {
        }
        
        public EliminarUsuarioRequestBody(int Id, string Remitente, int Origen) {
            this.Id = Id;
            this.Remitente = Remitente;
            this.Origen = Origen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Caja.ServiceUsuario.EliminarUsuarioResponseBody Body;
        
        public EliminarUsuarioResponse() {
        }
        
        public EliminarUsuarioResponse(Caja.ServiceUsuario.EliminarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EliminarUsuarioResult;
        
        public EliminarUsuarioResponseBody() {
        }
        
        public EliminarUsuarioResponseBody(bool EliminarUsuarioResult) {
            this.EliminarUsuarioResult = EliminarUsuarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioUsuarioSoapChannel : Caja.ServiceUsuario.ServicioUsuarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioUsuarioSoapClient : System.ServiceModel.ClientBase<Caja.ServiceUsuario.ServicioUsuarioSoap>, Caja.ServiceUsuario.ServicioUsuarioSoap {
        
        public ServicioUsuarioSoapClient() {
        }
        
        public ServicioUsuarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioUsuarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Caja.ServiceUsuario.EliminarUsuarioFirebaseResponse Caja.ServiceUsuario.ServicioUsuarioSoap.EliminarUsuarioFirebase(Caja.ServiceUsuario.EliminarUsuarioFirebaseRequest request) {
            return base.Channel.EliminarUsuarioFirebase(request);
        }
        
        public bool EliminarUsuarioFirebase(string email, string contrasena, string Remitente, int Origen) {
            Caja.ServiceUsuario.EliminarUsuarioFirebaseRequest inValue = new Caja.ServiceUsuario.EliminarUsuarioFirebaseRequest();
            inValue.Body = new Caja.ServiceUsuario.EliminarUsuarioFirebaseRequestBody();
            inValue.Body.email = email;
            inValue.Body.contrasena = contrasena;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            Caja.ServiceUsuario.EliminarUsuarioFirebaseResponse retVal = ((Caja.ServiceUsuario.ServicioUsuarioSoap)(this)).EliminarUsuarioFirebase(inValue);
            return retVal.Body.EliminarUsuarioFirebaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Caja.ServiceUsuario.EliminarUsuarioFirebaseResponse> Caja.ServiceUsuario.ServicioUsuarioSoap.EliminarUsuarioFirebaseAsync(Caja.ServiceUsuario.EliminarUsuarioFirebaseRequest request) {
            return base.Channel.EliminarUsuarioFirebaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Caja.ServiceUsuario.EliminarUsuarioFirebaseResponse> EliminarUsuarioFirebaseAsync(string email, string contrasena, string Remitente, int Origen) {
            Caja.ServiceUsuario.EliminarUsuarioFirebaseRequest inValue = new Caja.ServiceUsuario.EliminarUsuarioFirebaseRequest();
            inValue.Body = new Caja.ServiceUsuario.EliminarUsuarioFirebaseRequestBody();
            inValue.Body.email = email;
            inValue.Body.contrasena = contrasena;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((Caja.ServiceUsuario.ServicioUsuarioSoap)(this)).EliminarUsuarioFirebaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Caja.ServiceUsuario.IniciarSesionFirebaseResponse Caja.ServiceUsuario.ServicioUsuarioSoap.IniciarSesionFirebase(Caja.ServiceUsuario.IniciarSesionFirebaseRequest request) {
            return base.Channel.IniciarSesionFirebase(request);
        }
        
        public string IniciarSesionFirebase(string email, string contrasena, string Remitente, int Origen) {
            Caja.ServiceUsuario.IniciarSesionFirebaseRequest inValue = new Caja.ServiceUsuario.IniciarSesionFirebaseRequest();
            inValue.Body = new Caja.ServiceUsuario.IniciarSesionFirebaseRequestBody();
            inValue.Body.email = email;
            inValue.Body.contrasena = contrasena;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            Caja.ServiceUsuario.IniciarSesionFirebaseResponse retVal = ((Caja.ServiceUsuario.ServicioUsuarioSoap)(this)).IniciarSesionFirebase(inValue);
            return retVal.Body.IniciarSesionFirebaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Caja.ServiceUsuario.IniciarSesionFirebaseResponse> Caja.ServiceUsuario.ServicioUsuarioSoap.IniciarSesionFirebaseAsync(Caja.ServiceUsuario.IniciarSesionFirebaseRequest request) {
            return base.Channel.IniciarSesionFirebaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Caja.ServiceUsuario.IniciarSesionFirebaseResponse> IniciarSesionFirebaseAsync(string email, string contrasena, string Remitente, int Origen) {
            Caja.ServiceUsuario.IniciarSesionFirebaseRequest inValue = new Caja.ServiceUsuario.IniciarSesionFirebaseRequest();
            inValue.Body = new Caja.ServiceUsuario.IniciarSesionFirebaseRequestBody();
            inValue.Body.email = email;
            inValue.Body.contrasena = contrasena;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((Caja.ServiceUsuario.ServicioUsuarioSoap)(this)).IniciarSesionFirebaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Caja.ServiceUsuario.IngresarUsuarioResponse Caja.ServiceUsuario.ServicioUsuarioSoap.IngresarUsuario(Caja.ServiceUsuario.IngresarUsuarioRequest request) {
            return base.Channel.IngresarUsuario(request);
        }
        
        public bool IngresarUsuario(Caja.ServiceUsuario.Usuario user, string Remitente, int Origen) {
            Caja.ServiceUsuario.IngresarUsuarioRequest inValue = new Caja.ServiceUsuario.IngresarUsuarioRequest();
            inValue.Body = new Caja.ServiceUsuario.IngresarUsuarioRequestBody();
            inValue.Body.user = user;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            Caja.ServiceUsuario.IngresarUsuarioResponse retVal = ((Caja.ServiceUsuario.ServicioUsuarioSoap)(this)).IngresarUsuario(inValue);
            return retVal.Body.IngresarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Caja.ServiceUsuario.IngresarUsuarioResponse> Caja.ServiceUsuario.ServicioUsuarioSoap.IngresarUsuarioAsync(Caja.ServiceUsuario.IngresarUsuarioRequest request) {
            return base.Channel.IngresarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Caja.ServiceUsuario.IngresarUsuarioResponse> IngresarUsuarioAsync(Caja.ServiceUsuario.Usuario user, string Remitente, int Origen) {
            Caja.ServiceUsuario.IngresarUsuarioRequest inValue = new Caja.ServiceUsuario.IngresarUsuarioRequest();
            inValue.Body = new Caja.ServiceUsuario.IngresarUsuarioRequestBody();
            inValue.Body.user = user;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((Caja.ServiceUsuario.ServicioUsuarioSoap)(this)).IngresarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Caja.ServiceUsuario.ObtenerUsuarioResponse Caja.ServiceUsuario.ServicioUsuarioSoap.ObtenerUsuario(Caja.ServiceUsuario.ObtenerUsuarioRequest request) {
            return base.Channel.ObtenerUsuario(request);
        }
        
        public string ObtenerUsuario(string Usuario, string Remitente, int Origen) {
            Caja.ServiceUsuario.ObtenerUsuarioRequest inValue = new Caja.ServiceUsuario.ObtenerUsuarioRequest();
            inValue.Body = new Caja.ServiceUsuario.ObtenerUsuarioRequestBody();
            inValue.Body.Usuario = Usuario;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            Caja.ServiceUsuario.ObtenerUsuarioResponse retVal = ((Caja.ServiceUsuario.ServicioUsuarioSoap)(this)).ObtenerUsuario(inValue);
            return retVal.Body.ObtenerUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Caja.ServiceUsuario.ObtenerUsuarioResponse> Caja.ServiceUsuario.ServicioUsuarioSoap.ObtenerUsuarioAsync(Caja.ServiceUsuario.ObtenerUsuarioRequest request) {
            return base.Channel.ObtenerUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Caja.ServiceUsuario.ObtenerUsuarioResponse> ObtenerUsuarioAsync(string Usuario, string Remitente, int Origen) {
            Caja.ServiceUsuario.ObtenerUsuarioRequest inValue = new Caja.ServiceUsuario.ObtenerUsuarioRequest();
            inValue.Body = new Caja.ServiceUsuario.ObtenerUsuarioRequestBody();
            inValue.Body.Usuario = Usuario;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((Caja.ServiceUsuario.ServicioUsuarioSoap)(this)).ObtenerUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Caja.ServiceUsuario.ActualizarUsuarioResponse Caja.ServiceUsuario.ServicioUsuarioSoap.ActualizarUsuario(Caja.ServiceUsuario.ActualizarUsuarioRequest request) {
            return base.Channel.ActualizarUsuario(request);
        }
        
        public bool ActualizarUsuario(Caja.ServiceUsuario.Usuario user, string CorreoAnterior, string UsuaioAnterior, string Remitente, int Origen) {
            Caja.ServiceUsuario.ActualizarUsuarioRequest inValue = new Caja.ServiceUsuario.ActualizarUsuarioRequest();
            inValue.Body = new Caja.ServiceUsuario.ActualizarUsuarioRequestBody();
            inValue.Body.user = user;
            inValue.Body.CorreoAnterior = CorreoAnterior;
            inValue.Body.UsuaioAnterior = UsuaioAnterior;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            Caja.ServiceUsuario.ActualizarUsuarioResponse retVal = ((Caja.ServiceUsuario.ServicioUsuarioSoap)(this)).ActualizarUsuario(inValue);
            return retVal.Body.ActualizarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Caja.ServiceUsuario.ActualizarUsuarioResponse> Caja.ServiceUsuario.ServicioUsuarioSoap.ActualizarUsuarioAsync(Caja.ServiceUsuario.ActualizarUsuarioRequest request) {
            return base.Channel.ActualizarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Caja.ServiceUsuario.ActualizarUsuarioResponse> ActualizarUsuarioAsync(Caja.ServiceUsuario.Usuario user, string CorreoAnterior, string UsuaioAnterior, string Remitente, int Origen) {
            Caja.ServiceUsuario.ActualizarUsuarioRequest inValue = new Caja.ServiceUsuario.ActualizarUsuarioRequest();
            inValue.Body = new Caja.ServiceUsuario.ActualizarUsuarioRequestBody();
            inValue.Body.user = user;
            inValue.Body.CorreoAnterior = CorreoAnterior;
            inValue.Body.UsuaioAnterior = UsuaioAnterior;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((Caja.ServiceUsuario.ServicioUsuarioSoap)(this)).ActualizarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Caja.ServiceUsuario.EliminarUsuarioResponse Caja.ServiceUsuario.ServicioUsuarioSoap.EliminarUsuario(Caja.ServiceUsuario.EliminarUsuarioRequest request) {
            return base.Channel.EliminarUsuario(request);
        }
        
        public bool EliminarUsuario(int Id, string Remitente, int Origen) {
            Caja.ServiceUsuario.EliminarUsuarioRequest inValue = new Caja.ServiceUsuario.EliminarUsuarioRequest();
            inValue.Body = new Caja.ServiceUsuario.EliminarUsuarioRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            Caja.ServiceUsuario.EliminarUsuarioResponse retVal = ((Caja.ServiceUsuario.ServicioUsuarioSoap)(this)).EliminarUsuario(inValue);
            return retVal.Body.EliminarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Caja.ServiceUsuario.EliminarUsuarioResponse> Caja.ServiceUsuario.ServicioUsuarioSoap.EliminarUsuarioAsync(Caja.ServiceUsuario.EliminarUsuarioRequest request) {
            return base.Channel.EliminarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Caja.ServiceUsuario.EliminarUsuarioResponse> EliminarUsuarioAsync(int Id, string Remitente, int Origen) {
            Caja.ServiceUsuario.EliminarUsuarioRequest inValue = new Caja.ServiceUsuario.EliminarUsuarioRequest();
            inValue.Body = new Caja.ServiceUsuario.EliminarUsuarioRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.Remitente = Remitente;
            inValue.Body.Origen = Origen;
            return ((Caja.ServiceUsuario.ServicioUsuarioSoap)(this)).EliminarUsuarioAsync(inValue);
        }
    }
}
